spring.application.name=main-ctx

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/metafilm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# End-user Firebase project
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/${FIREBASE_PROJECT_ID:sprite-6193a}

# Admin Firebase project
admin.firebase.project-id=${ADMIN_FIREBASE_PROJECT_ID:sprite-6193a}

logging.level.com.rsargsyan.metafilm=INFO

# S3
s3.access-key-id=${S3_ACCESS_KEY_ID}
s3.secret-access-key=${S3_SECRET_ACCESS_KEY}
s3.region=${S3_REGION:eu-central-003}
s3.endpoint=${S3_ENDPOINT:https://s3.eu-central-003.backblazeb2.com}
s3.bucket=${S3_BUCKET}

# TMDB
tmdb.api-key=${TMDB_API_KEY}
tmdb.base-url=https://api.themoviedb.org/3
tmdb.image-base-url=https://image.tmdb.org/t/p/original

# db-scheduler
db-scheduler.autocreate=true
