spring.application.name=main-ctx

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/metafilm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# End-user Firebase project
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/${FIREBASE_PROJECT_ID:metafilm}

# Admin Firebase project
admin.firebase.project-id=${ADMIN_FIREBASE_PROJECT_ID:metafilm-admin}

logging.level.com.rsargsyan.metafilm=INFO
